services:
  - type: web
    name: marine-guard-backend
    env: python
    rootDir: Marine-Guard-main/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CORS_ORIGINS
        value: "*"

  - type: web
    name: marine-guard-frontend
    env: static
    rootDir: Marine-Guard-main/frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://marine-guard-backend.onrender.com/api
