/**
 * Translations for Marine Safety Forecasting System
 * ==================================================
 * English and Tamil language support
 * 
 * Author: B.Tech AI&DS 
 * Date: 2026
 */

export const translations = {
  en: {
    // Header
    appTitle: "Marine & Coastal Safety Forecasting System",
    appSubtitle: "Tamil Nadu Coastal Districts",
    
    // District Selector
    selectDistrict: "Select District",
    districtPlaceholder: "Choose a coastal district...",
    
    // Current Conditions
    currentConditions: "Current Marine Conditions",
    waveHeight: "Wave Height",
    wavePeriod: "Wave Period",
    waveDirection: "Wave Direction",
    windSpeed: "Wind Speed",
    windDirection: "Wind Direction",
    temperature: "Temperature",
    humidity: "Humidity",
    pressure: "Pressure",
    meters: "m",
    seconds: "s",
    degrees: "°",
    kmh: "km/h",
    ms: "m/s",
    celsius: "°C",
    percent: "%",
    hPa: "hPa",
    
    // Safety Status
    safetyStatus: "Safety Status",
    safe: "Safe",
    caution: "Caution",
    dangerous: "Dangerous",
    safeDesc: "Good conditions for marine activities",
    cautionDesc: "Exercise caution, monitor conditions",
    dangerousDesc: "Unsafe conditions, avoid sea",
    recommendationsTitle: "Recommendations:",
    safeRecommendations: [
      "Suitable for fishing activities",
      "Normal coastal activities can proceed",
      "Continue monitoring conditions"
    ],
    cautionRecommendations: [
      "Avoid venturing far from shore",
      "Small boats should stay in harbor",
      "Keep monitoring weather updates"
    ],
    dangerousRecommendations: [
      "All fishing activities suspended",
      "Stay away from beaches",
      "Secure boats and equipment"
    ],
    unknownStatus: "Unable to determine safety status",
    unknownRecommendations: ["Please refresh data to get safety status"],
    
    // Wave Forecast
    waveForecastTitle: "Wave Height Forecast",
    waveForecast: "Wave Height Forecast (24 Hours)",
    currentHeight: "Current",
    maxHeight: "Maximum",
    avgHeight: "Average",
    forecastChart: "Forecast Chart",
    safeZone: "Safe Zone",
    cautionZone: "Caution Zone",
    dangerZone: "Danger Zone",
    noForecastData: "No forecast data available",
    waveHeightLabel: "Wave Height",
    statusLabel: "Status",
    safeLimit: "Safe Limit",
    dangerLimit: "Danger Limit",
    safeLegend: "Safe (< 1.0m)",
    cautionLegend: "Caution (1.0 - 2.5m)",
    dangerLegend: "Dangerous (> 2.5m)",
    heightLabel: "Height (m)",
    
    // AI Explanation
    aiAnalysis: "AI Safety Analysis",
    gptPowered: "GPT-4o",
    ruleBased: "Rule-based",
    azureOpenAI: "Analysis generated by Azure OpenAI GPT-4o",
    ruleBasedSystem: "Analysis generated using rule-based system",
    noExplanation: "No explanation available. Please refresh the data.",
    
    // District Overview
    districtOverview: "All Districts Overview",
    loading: "Loading district data...",
    loadingDistricts: "Fetching data for all 14 coastal districts...",
    clickToRetry: "Failed to load district overview. Click to retry.",
    retry: "Retry",
        // Wind Rose
    windRose: {
      title: "Wind Rose - Wind Direction Distribution",
      next24Hours: "Next 24 Hours",
      prevailingWind: "Prevailing Wind",
      frequency: "Frequency",
      avgSpeed: "Avg Speed",
      maxSpeed: "Max Speed",
      observations: "Observations",
      north: "North",
      northeast: "Northeast",
      east: "East",
      southeast: "Southeast",
      south: "South",
      southwest: "Southwest",
      west: "West",
      northwest: "Northwest",
      speedCategories: "Wind Speed Categories",
      light: "Light",
      moderate: "Moderate",
      strong: "Strong",
      noData: "No wind data available"
    },
        // Buttons
    refresh: "Refresh Data",
    predict: "Get Prediction",
    explain: "Get AI Explanation",
    
    // Districts
    districts: {
      "Thiruvallur": "Thiruvallur",
      "Chennai": "Chennai",
      "Kanchipuram": "Kanchipuram",
      "Chengalpattu": "Chengalpattu",
      "Villupuram": "Villupuram",
      "Cuddalore": "Cuddalore",
      "Mayiladuthurai": "Mayiladuthurai",
      "Nagapattinam": "Nagapattinam",
      "Thanjavur": "Thanjavur",
      "Tiruvarur": "Tiruvarur",
      "Ramanathapuram": "Ramanathapuram",
      "Thoothukudi": "Thoothukudi",
      "Tirunelveli": "Tirunelveli",
      "Kanniyakumari": "Kanniyakumari"
    }
  },
  
  ta: {
    // Header
    appTitle: "கடல் மற்றும் கடலோர பாதுகாப்பு முன்னறிவிப்பு அமைப்பு",
    appSubtitle: "தமிழ்நாடு கடலோர மாவட்டங்கள்",
    
    // District Selector
    selectDistrict: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    districtPlaceholder: "கடலோர மாவட்டத்தைத் தேர்வு செய்யவும்...",
    
    // Current Conditions
    currentConditions: "தற்போதைய கடல் நிலைமைகள்",
    waveHeight: "அலை உயரம்",
    wavePeriod: "அலை கால அளவு",
    waveDirection: "அலை திசை",
    windSpeed: "காற்றின் வேகம்",
    windDirection: "காற்றின் திசை",
    temperature: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    pressure: "அழுத்தம்",
    meters: "மீ",
    seconds: "வி",
    degrees: "°",
    kmh: "கி.மீ/ம",
    ms: "மீ/வி",
    celsius: "°செ",
    percent: "%",
    hPa: "hPa",
    
    // Safety Status
    safetyStatus: "பாதுகாப்பு நிலை",
    safe: "பாதுகாப்பானது",
    caution: "எச்சரிக்கை",
    dangerous: "ஆபத்தானது",
    safeDesc: "கடல் செயல்பாடுகளுக்கு நல்ல சூழ்நிலை",
    cautionDesc: "எச்சரிக்கையுடன் இருக்கவும், நிலைமைகளை கண்காணிக்கவும்",
    dangerousDesc: "பாதுகாப்பற்ற சூழ்நிலை, கடலை தவிர்க்கவும்",
    recommendationsTitle: "பரிந்துரைகள்:",
    safeRecommendations: [
      "மீன்பிடி செயல்பாடுகளுக்கு ஏற்றது",
      "சாதாரண கடலோர செயல்பாடுகள் தொடரலாம்",
      "நிலைமைகளை தொடர்ந்து கண்காணிக்கவும்"
    ],
    cautionRecommendations: [
      "கடற்கரையில் இருந்து வெகு தொலைவு செல்ல வேண்டாம்",
      "சிறிய படகுகள் கடற்கரையில் இருக்க வேண்டும்",
      "வானிலை புதுப்பிப்புகளை கண்காணிக்கவும்"
    ],
    dangerousRecommendations: [
      "அனைத்து மீன்பிடி செயல்பாடுகளும் நிறுத்தப்பட்டுள்ளன",
      "கடற்கரைகளில் இருந்து விலகி இருக்கவும்",
      "படகுகள் மற்றும் உபகரணங்களை பாதுகாப்பாக வைக்கவும்"
    ],
    unknownStatus: "பாதுகாப்பு நிலையை தீர்மானிக்க முடியவில்லை",
    unknownRecommendations: ["பாதுகாப்பு நிலையைப் பெற தரவை புதுப்பிக்கவும்"],
    
    // Wave Forecast
    waveForecastTitle: "அலை உயர முன்னறிவிப்பு",
    waveForecast: "அலை உயர முன்னறிவிப்பு (24 மணிநேரம்)",
    currentHeight: "தற்போதைய",
    maxHeight: "அதிகபட்சம்",
    avgHeight: "சராசரி",
    forecastChart: "முன்னறிவிப்பு விளக்கப்படம்",
    safeZone: "பாதுகாப்பு வலயம்",
    cautionZone: "எச்சரிக்கை வலயம்",
    dangerZone: "ஆபத்து வலயம்",
    noForecastData: "முன்னறிவிப்பு தரவு கிடைக்கவில்லை",
    waveHeightLabel: "அலை உயரம்",
    statusLabel: "நிலை",
    safeLimit: "பாதுகாப்பு எல்லை",
    dangerLimit: "ஆபத்து எல்லை",
    safeLegend: "பாதுகாப்பானது (< 1.0மீ)",
    cautionLegend: "எச்சரிக்கை (1.0 - 2.5மீ)",
    dangerLegend: "ஆபத்தானது (> 2.5மீ)",
    heightLabel: "உயரம் (மீ)",
    
    // AI Explanation
    aiAnalysis: "செயற்கை நுண்ணறிவு பாதுகாப்பு பகுப்பாய்வு",
    gptPowered: "GPT-4o",
    ruleBased: "விதி அடிப்படையிலான",
    azureOpenAI: "Azure OpenAI GPT-4o மூலம் உருவாக்கப்பட்ட பகுப்பாய்வு",
    ruleBasedSystem: "விதி அடிப்படையிலான அமைப்பு மூலம் உருவாக்கப்பட்ட பகுப்பாய்வு",
    noExplanation: "விளக்கம் கிடைக்கவில்லை. தயவுசெய்து தரவை புதுப்பிக்கவும்.",
    
    // District Overview
    districtOverview: "அனைத்து மாவட்ட மேலோட்டம்",
    loading: "மாவட்ட தரவு ஏற்றப்படுகிறது...",
    loadingDistricts: "14 கடலோர மாவட்டங்களுக்கான தரவு பெறப்படுகிறது...",
    clickToRetry: "மாவட்ட மேலோட்டத்தை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்க கிளிக் செய்யவும்.",
    retry: "மீண்டும் முயற்சிக்கவும்",
    
    // Wind Rose
    windRose: {
      title: "காற்று திசை விநியோகம்",
      next24Hours: "அடுத்த 24 மணிநேரம்",
      prevailingWind: "முக்கிய காற்று திசை",
      frequency: "அதிர்வெண்",
      avgSpeed: "சராசரி வேகம்",
      maxSpeed: "அதிகபட்ச வேகம்",
      observations: "கண்காணிப்புகள்",
      north: "வடக்கு",
      northeast: "வடகிழக்கு",
      east: "கிழக்கு",
      southeast: "தென்கிழக்கு",
      south: "தெற்கு",
      southwest: "தென்மேற்கு",
      west: "மேற்கு",
      northwest: "வடமேற்கு",
      speedCategories: "காற்று வேக வகைகள்",
      light: "லேசான",
      moderate: "மிதமான",
      strong: "வலுவான",
      noData: "காற்று தரவு இல்லை"
    },
    
    // Buttons
    refresh: "தரவை புதுப்பிக்கவும்",
    predict: "முன்னறிவிப்பைப் பெறவும்",
    explain: "AI விளக்கத்தைப் பெறவும்",
    
    // Districts (Tamil names)
    districts: {
      "Thiruvallur": "திருவள்ளூர்",
      "Chennai": "சென்னை",
      "Kanchipuram": "காஞ்சிபுரம்",
      "Chengalpattu": "செங்கல்பட்டு",
      "Villupuram": "விழுப்புரம்",
      "Cuddalore": "கடலூர்",
      "Mayiladuthurai": "மயிலாடுதுறை",
      "Nagapattinam": "நாகப்பட்டினம்",
      "Thanjavur": "தஞ்சாவூர்",
      "Tiruvarur": "திருவாரூர்",
      "Ramanathapuram": "இராமநாதபுரம்",
      "Thoothukudi": "தூத்துக்குடி",
      "Tirunelveli": "திருநெல்வேலி",
      "Kanniyakumari": "கன்னியாகுமரி"
    }
  }
};

export default translations;
